### ISSUE TITLE
Why are the addresses different from the main site?

### ISSUE THREAD

**Issue by allg97** [amirinsight/py-bingx#1]
Hello
Excuse my initial question...
But why are all the API addresses in this package different from the site itself?
Can I paste the URLs of the main site and use it like that?
What is the reason for this difference?
Thank you for answering

**Comment by amirinsight** [comment]
Hi
BingX uses a different domain for their API which is `https://open-api.bingx.com`. This is a common practice in building APIs. 
You can't send your API requests to `https://bingx.com`. The API is not running on that URL and you won't get a response.

I built this package by using this documentation as reference: `https://bingx-api.github.io/docs/#/swapV2`

Your questions are very welcome. Feel free to ask more.

**Comment by amirinsight** [comment]
I'm closing this since it's not an issue but simply a question.
If you have a question please use [Github Community Q&A](https://github.com/amirinsight/py-bingx/discussions/categories/q-a).
