### ISSUE TITLE
place_trigger_market_order() or open_market_order() 

### ISSUE THREAD

**Issue by tolaku** [amirinsight/py-bingx#8]
Очень заинтересовала Ваша проделанная работа. Помогите пожалуйста отправлять запрос с помощью этой функции place_trigger_market_order() или open_market_order() 
1. Цель моей задачи, редактировать или устанавливать при открывание сделки TAKE_PROFIT или как я понял она еще называется tp. 
2. Но как можно TAKE_PROFIT отправить виде процента допустим 5%?

Благодарю за любую помощь!

**Comment by amirinsight** [comment]
Thank you for your interest,

py-bingx doesn't accept percentages so you should calculate your desired tp price before using the function you mentioned.

You can achieve this by something like this:

```python
# tp_percent should be between 1 and 100
def tp_percent_to_price(entry_price, tp_percent):
    tp_price = entry_price + entry_price*tp_percent/100
    return tp_price
```

**Comment by tolaku** [comment]
Вы не знаете в чем может быть проблема. Все работало прекрасно, а сегодня при отправке любой команды, допустим order_data = bingx.get_my_perpetual_swap_positions('BTC-USDT')
order_data = bingx.get_perpetual_balance()

Я получаю вот такой ответ: 
{'error': True, 'response': {'code': 100421, 'msg': 'Null timestamp or timestamp mismatch', 'timestamp': 1714168336504}}
или вот такой:
{'code': 100421, 'msg': 'Null timestamp or timestamp mismatch', 'timestamp': 1714168389737}

Помогите пожалуйста, почему появилась данная проблема? Благодарю. 

На другом компьютере отправляю вот эту команду: 
order_data = bingx.get_my_perpetual_swap_positions('BTC-USDT') 
print(order_data)
получаю ответ пустой массив {} хотя сделка там есть, и она открыта. Раньше все было отлично, что случилось такое сегодня, что перестало работать?

**Comment by tolaku** [comment]
Но если отправляешь запрос на открывание сделки, тогда все отлично отрабатывает.
вот отправил: 
order_data = bingx.open_market_order('BTC-USDT', 'LONG', 0.0001, tp=tp_t)
print(order_data)
и получил отличный ответ:
{'orderId': 1784158993939177472, 'symbol': 'BTC-USDT', 'positionSide': 'LONG', 'side': 'BUY', 'type': 'MARKET', 'price': 0, 'quantity': 0.0001, 'stopPrice': 0, 'workingType': 'MARK_PRICE', 'clientOrderID': '', 'timeInForce': 'GTC', 'priceRate': 0, 'stopLoss': '', 'takeProfit': '{"type": "TAKE_PROFIT_MARKET", "quantity": 0.0001,"stopPrice": 63204.7116,"price": 63204.7116,"workingType":"MARK_PRICE"}', 'reduceOnly': False, 'activationPrice': 0, 'closePosition': '', 'stopGuaranteed': ''}

А когда отправляешь как я выше Вам писал, допустим вот этот запрос: 
order_data = bingx.get_my_perpetual_swap_positions('BTC-USDT')
print(order_data)

получает ответ:
{}

А когда вот этот запрос:
order_data = bingx.get_perpetual_balance()
print(order_data)

получаю ответ вот такой:
{'code': 80014, 'msg': 'timestamp is invalid', 'data': {}}

Извините что повторно отправляю Вам комментарий, хотел сказать, что при открытие сделки (open_market_order('BTC-USDT', 'LONG', 0.0001, tp=tp_t)) запрос отлично отрабатывает, а когда нужно узнать get_my_perpetual_swap_positions('BTC-USDT'), получают пустой массив {}, либо баланс узнать, получают код ошибки {'code': 80014, 'msg': 'timestamp is invalid', 'data': {}}. Раньше все работало отлично. Может мне в техническую поддержку bingx.com написать, что скажите?

**Comment by amirinsight** [comment]
If this used to work before, it might be due to some changes on bingx api.

Also I'm closing this as it is not an issue but a question. If you have further questions feel free to ask them on [Github Community Q&A for py-bingx](https://github.com/amirinsight/py-bingx/discussions/categories/q-a).
